development:
  adapter: postgresql
  encoding: unicode
  database: offers_development
  host: localhost
  username: offers

test:
  adapter: postgresql
  encoding: unicode
  database: offers_test
  host: localhost
  username: offers
